### ISSUE TITLE
Not in rubygems

### ISSUE THREAD

**Issue by kakoni** [jukkakoskinen/mycashflow-ruby#1]
Hi! So this gem is not in rubygems, therefore ```gem install mycashflow``` wouldnt work.

**Comment by jukkakoskinen** [comment]
Hey! True, I haven't gotten the time to work on this as much as I'd like. I'll submit this to the RubyGems ASAP. Meanwhile if you're using Bundler, you can use this repo directly as described in http://bundler.io/git.html.

**Comment by jukkakoskinen** [comment]
Here we go: https://rubygems.org/gems/mycashflow

**Comment by jukkakoskinen** [comment]
Closing this, but please let me know if you have any other questions.
